language: python
python:
    - "2.7"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install coveralls
    - pip install pep8
    - pip install tox
    - pip install -r requirements.txt
    - make
script:
    - pep8 plexcleaner/* test/* --ignore E501
    - py.test
    - coverage run test/test_media_library.py
    - coverage run test/test_media_movie.py
after_success:
    - coveralls