language: python
python:
    - "2.7"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install -r requirements.txt
    - pip install tox
    - pip install coveralls
    - pip install pytest
    - pip install pytest-cov
    - pip install flake8
script:
    - python setup.py test
after_success:
    - coveralls
