language: python
python:
    - "2.7"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install coveralls
    - pip install tox
    - pip install flake8
    - pip install pyjarowinkler
script:
    - coverage erase
    - coverage run -p setup.py test
    - coverage combine
after_success:
    - coveralls
