language: python
python:
    - "2.7"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install coveralls
    - pip install pep8
    - pip install tox
    - pip install -r requirements.txt
script:
    - pep8 plexcleaner/* test/* --ignore E501
    - coverage erase
    - coverage run -p setup.py test
    - coverage combine
after_success:
    - coveralls